rig_vel_controller:
    type: "diff_drive_controller/DiffDriveController"
    publish_rate: 50

    left_wheel: ['wheel_middle_left_joint','wheel_back_left_joint', 'wheel_front_left_joint']
    right_wheel: ['wheel_back_right_joint', 'wheel_middle_right_joint', 'wheel_front_right_joint']
    wheel_separation : 0.32
    wheel_radius : 0.125
    wheel_radius_multiplier: 1.0
    # Odometry covariances for the encoder output of the robot. These values should
    # be tuned to your robot's sample odometry data, but these values are a good place
    # to start
    pose_covariance_diagonal : [0.001, 0.001, 0.0, 0.0, 0.0, 0.0]
    twist_covariance_diagonal: [0.001, 0.001, 0.0, 0.0, 0.0, 0.0]

    # Velocity commands timeout [s], default 0.5
    cmd_vel_timeout: 0.25

    # Top level frame (link) of the robot description
    base_frame_id: base_footprint

    enable_odom_tf: false
    odom_frame_id: encoder_odom

    # Velocity and acceleration limits for the robot
    linear:
      x:
        has_velocity_limits    : true
        max_velocity           : 0.3   # m/s
        has_acceleration_limits: true
        max_acceleration       : 5.0   # m/s^2
    angular:
      z:
        has_velocity_limits    : true
        max_velocity           : 0.2   # rad/s
        has_acceleration_limits: true
        max_acceleration       : 0.2   # rad/s^2






