joint_state_controller:
  # The joint state controller handles publishing transforms for any moving joints
  type: "joint_state_controller/JointStateController"
  publish_rate: 50

# Position controller
joint_position_controller:
  type: effort_controllers/JointPositionController
  joint: front_joint_middle
  pid: {p: 1000.0, i: 1.000, d: 1.00}
joint_position_controller2:
  type: effort_controllers/JointPositionController
  joint: middle_joint_back
  pid: {p: 100.0, i: 1.0, d: 1.00}

